AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/{rails,rake,bundle}'
    - node_modules/**/*
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/**/*
    
Layout/LineLength:
  Max: 99
  Exclude: 
    - spec/support/database_cleaner.rb
    - db/**/*
    - config/**/*
    
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - app/admin/**/*
    - app/my/**/*
    - app/controllers/concerns/**/*
    - app/models/concerns/**/*
    - app/services/concerns/**/*
    
Metrics/MethodLength:
  Max: 20
  
Metrics/AbcSize:
  Max: 30