version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/slapp_data
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/slapp_data
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
  - location: scripts/after_build.sh
    runas: ubuntu

