default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_IP'] %>

development:
  <<: *default
  database: slapp_data_dev

test:
  <<: *default
  database: slapp_data_test
  
sl-development:
  <<: *default
  database: slapp_data_sl_development

production:
  <<: *default
  database: slapp_data_production