default:  
  web_object:
    api_key:  <%= ENV.fetch('API_KEY') %>        # The string used as a shared key for encryption
    inactive_limit: 30              # How long from the last ping the object is considered active